version: '3.1'
services:
  db:
    image: postgres:14-alpine
    container_name: db
    ports:
      - "5432:5432"
    env_file:
      - .env

  main:
    build: .
    image: main
    container_name: main
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file:
      - .env