version: '3.1'
services:
  db:
    image: postgres:14-alpine
    container_name: db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=budget
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root

  main:
    build: .
    image: main
    container_name: main
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/budget
      - SPRING_DATASOURCE_USER=postgres
      - SPRING_DATASOURCE_PASSWORD=root